name: PumpCore
version: 3.0
main: me.server.bonus.Main
api-version: 1.16

commands:
  admin:
  fly:
  heal:
  feed:
  coords:
  ping:
  rtp:
  back:
  tpa:
  tpaccept:
  tpdeny:
  shop:
  wand:
  set:
  rg:
